---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: policyvalidator-claim
  namespace: policycenter
  labels:
    app: policyvalidator
spec:
  storageClassName: gp2 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: policyvalidator-service
  namespace: policycenter
  labels:
    app: policyvalidator
spec:
  selector:
    app: policyvalidator
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policyvalidator-deployment
  namespace: policycenter
  labels:
    app: policyvalidator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policyvalidator
  template:
    metadata:
      labels:
        app: policyvalidator
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "policyvalidator"
        dapr.io/app-port: "8000"
        dapr.io/app-protocol: "http"
    spec:
      containers:
      - name: policyvalidator
        image: 466855634803.dkr.ecr.us-west-2.amazonaws.com/dapr/policyvalidator:0.0.16
        imagePullPolicy: Always
        volumeMounts:
        - name: persistent-storage
          mountPath: /kyvernocli
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "250m"
          limits:
            memory: "1.0Gi"
            cpu: "1.0"
        env:
        - name: TEST_MODE
          value: "False"
        - name: DONT_CLEANUP
          value: "True"
        - name: PATH_TO_RESOURCES
          value: "/kyvernocli"
        - name: PATH_TO_KYVERNO_POLICIES
          value: "/kyvernocli"
        - name: KYVERNO_REPO
          value: "smitterh"
        - name: DAPR_URL
          value: "localhost"
        - name: DAPR_SECRET_STORE
          value: "awssecretmanager"
        - name: GITHUB_SECRET
          value: github-smitterh-readonly
        - name: DLOCK_EXPIRY_SECONDS
          value: "60"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: policyvalidator-claim
