apiVersion: fico.org/v1alpha1
apiVersion: fico.org/v1alpha1
kind: XPlatformTenantClaim
metadata:
  name: my-platform-tenant
spec:
  parameters:
    pulsarTenant:
      pulsarConnection: pulsar-connection
      pulsarClusterNamespace: pulsar-1 
      pulsarTenantId: tenant-1234567
      pulsarNamespace: tenant-1234567-mynamespace
      pulsarTopic: tenant-1234567-mytopic
  compositionRef:
    name: create-platform-tenant-with-validation