apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: create-platform-tenant-with-validation
spec:
  compositeTypeRef:
    apiVersion: fico.org/v1alpha1
    kind: XPlatformTenant
  mode: Pipeline
  pipeline:
  - step: validate-policies-platform-tenant
    functionRef:
      name: function-policy-validation