apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: create-platform-tenant
spec:
  compositeTypeRef:
    apiVersion: fico.org/v1alpha1
    kind: XPlatformTenant
  mode: Pipeline
  pipeline:
  - step: run-function-tenant-statestore
    functionRef:
      name: function-tenant-statestore
