---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: function-event-services-inputs.template.fn.crossplane.io
spec:
  group: template.fn.crossplane.io
  names:
    categories:
    - crossplane
    kind: Input
    listKind: InputList
    plural: function-event-services-inputs
    singular: function-event-services-input
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Input can be used to provide input to this Function.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          watch:
            description: Which composite resource is this function-event-service watching to achieve a Ready state
            type: string
          expiryInSeconds: 
            description: The duration of the lock in seconds. This lock is used to capture a single Ready state for the composite resource being watched
            type: integer
            minimum: 0
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
        required:
        - watch
        type: object
    served: true
    storage: true
