apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: keyPrefix
    value: none
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
